In [173]:
import numpy as np 
import pandas as pd

In [175]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [176]:
movies.head(5)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [179]:
movies.shape

(4803, 20)

In [181]:
credits.head(5)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [183]:
credits.shape

(4803, 4)

In [185]:
movies = movies.merge(credits,on='title')

In [187]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [189]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [191]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [193]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [195]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [197]:
import ast

In [199]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [201]:
movies.dropna(inplace=True)

In [203]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [205]:
movies['genres'] = movies['genres'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [207]:
movies['keywords'] = movies['keywords'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [311]:
def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L

In [313]:
movies['cast'] = movies['cast'].apply(convert)
movies.head()

ValueError: malformed node or string: ['[', '{', '"']

In [215]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [217]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [218]:
movies.sample(5)

,movie_id,title,overview,genres,keywords,cast,crew
3769,184345,A Haunted House 2,"Having exorcised the demons of his ex, Malcolm...","[Comedy, Horror]",[haunted house],"[{""",[Michael Tiddes]
3027,14544,Roll Bounce,"From Wikipedia, the free encyclopedia. Roll Bo...","[Comedy, Drama, Family]",[],"[{""",[Malcolm D. Lee]
981,421,The Life Aquatic with Steve Zissou,Wes Anderson’s incisive quirky comedy build up...,"[Adventure, Comedy, Drama]","[ocean, film making, loss of mother, cynic, re...","[{""",[Wes Anderson]
4680,194588,Short Cut to Nirvana: Kumbh Mela,Every 12 years over 70 million pilgrims gather...,[],[],[],[]
2899,41508,Fateless,An Hungarian youth comes of age at Buchenwald ...,"[War, Drama]","[budapest, hungary, concentration camp, world ...","[{""",[Lajos Koltai]

In [219]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [220]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [221]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[[, {, ""]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[[, {, ""]",[GoreVerbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[[, {, ""]",[SamMendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[[, {, ""]",[ChristopherNolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[[, {, ""]",[AndrewStanton]

In [222]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [229]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [231]:
new = movies.drop(columns=['overview','genres','keywords','cast','crew'])

In [233]:
new['tags'] = new['tags'].apply(lambda x: " ".join(x))
new.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [235]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [237]:
vector = cv.fit_transform(new['tags']).toarray()

In [239]:
vector.shape

(4806, 5000)

In [241]:
from sklearn.metrics.pairwise import cosine_similarity

In [243]:
similarity = cosine_similarity(vector)

In [244]:
similarity[0]

array([1.        , 0.09284767, 0.06085806, ..., 0.02431083, 0.02635231,
       0.        ])

In [309]:
list(enumerate(similarity[0]))

[(0, 1.0),
 (1, 0.09284766908852593),
 (2, 0.06085806194501845),
 (3, 0.0401286176952564),
 (4, 0.17791499872137212),
 (5, 0.12028130608117205),
 (6, 0.019779694303230885),
 (7, 0.1800205749557739),
 (8, 0.0629940788348712),
 (9, 0.07624928516630233),
 (10, 0.11973686801784994),
 (11, 0.08111071056538127),
 (12, 0.1),
 (13, 0.04714045207910317),
 (14, 0.11433239009500587),
 (15, 0.045360921162651446),
 (16, 0.08451542547285165),
 (17, 0.15061601901917732),
 (18, 0.11340230290662862),
 (19, 0.08535791995526398),
 (20, 0.05773502691896257),
 (21, 0.09284766908852593),
 (22, 0.06950480468569159),
 (23, 0.1),
 (24, 0.057166195047502935),
 (25, 0.05360562674188974),
 (26, 0.17407765595569785),
 (27, 0.1849000654084097),
 (28, 0.12379689211803457),
 (29, 0.07142857142857142),
 (30, 0.07372097807744857),
 (31, 0.16666666666666666),
 (32, 0.09157370929912602),
 (33, 0.10910894511799618),
 (34, 0.0),
 (35, 0.10206207261596575),
 (36, 0.18220272220337375),
 (37, 0.08574929257125441),
 (38, 0.0629940788348712),
 (39, 0.08980265101338746),
 (40, 0.057166195047502935),
 (41, 0.14744195615489714),
 (42, 0.0),
 (43, 0.09829463743659808),
 (44, 0.043033148291193514),
 (45, 0.08989331499509895),
 (46, 0.18257418583505536),
 (47, 0.19528336647123581),
 (48, 0.06741998624632421),
 (49, 0.06537204504606134),
 (50, 0.12379689211803457),
 (51, 0.08466675133346033),
 (52, 0.16439898730535726),
 (53, 0.049690399499995326),
 (54, 0.034752402342845795),
 (55, 0.07453559924999298),
 (56, 0.14907119849998596),
 (57, 0.028583097523751468),
 (58, 0.046676002800933654),
 (59, 0.07968190728895957),
 (60, 0.029012942659282975),
 (61, 0.22360679774997894),
 (62, 0.08333333333333333),
 (63, 0.08399210511316159),
 (64, 0.03268602252303067),
 (65, 0.021166687833365082),
 (66, 0.024845199749997663),
 (67, 0.17677669529663687),
 (68, 0.14213381090374028),
 (69, 0.05103103630798288),
 (70, 0.08333333333333333),
 (71, 0.08703882797784893),
 (72, 0.12379689211803457),
 (73, 0.03726779962499649),
 (74, 0.22613350843332272),
 (75, 0.08980265101338746),
 (76, 0.07905694150420949),
 (77, 0.014617633655117155),
 (78, 0.052057920629535355),
 (79, 0.07905694150420949),
 (80, 0.03456505649101417),
 (81, 0.11624763874381927),
 (82, 0.08333333333333333),
 (83, 0.22116293423234568),
 (84, 0.14470719035407653),
 (85, 0.1066003581778052),
 (86, 0.09128709291752768),
 (87, 0.1160517706371319),
 (88, 0.08980265101338746),
 (89, 0.060357164028345685),
 (90, 0.06415002990995841),
 (91, 0.16037507477489604),
 (92, 0.07001400420140048),
 (93, 0.050832856777534886),
 (94, 0.13333333333333333),
 (95, 0.1270821419438372),
 (96, 0.0944911182523068),
 (97, 0.07372097807744857),
 (98, 0.08451542547285165),
 (99, 0.029934217004462485),
 (100, 0.07647191129018724),
 (101, 0.09128709291752768),
 (102, 0.11135885079684349),
 (103, 0.08753762190648169),
 (104, 0.05892556509887895),
 (105, 0.11180339887498947),
 (106, 0.045360921162651446),
 (107, 0.09072184232530289),
 (108, 0.16839382851364085),
 (109, 0.07856742013183862),
 (110, 0.024845199749997663),
 (111, 0.1496710850223124),
 (112, 0.09284766908852593),
 (113, 0.05270462766947299),
 (114, 0.052057920629535355),
 (115, 0.0563436169819011),
 (116, 0.0563436169819011),
 (117, 0.06085806194501845),
 (118, 0.017282528245507085),
 (119, 0.048621663832631515),
 (120, 0.0),
 (121, 0.09284766908852593),
 (122, 0.09805806756909201),
 (123, 0.12155415958157878),
 (124, 0.06741998624632421),
 (125, 0.0763915414190176),
 (126, 0.1178511301977579),
 (127, 0.13562224520112248),
 (128, 0.0),
 (129, 0.10540925533894598),
 (130, 0.032075014954979206),
 (131, 0.1126872339638022),
 (132, 0.045360921162651446),
 (133, 0.03268602252303067),
 (134, 0.13900960937138318),
 (135, 0.0),
 (136, 0.023809523809523808),
 (137, 0.034380708208626445),
 (138, 0.08111071056538127),
 (139, 0.10669739994407998),
 (140, 0.05143444998736397),
 (141, 0.11470786693528086),
 (142, 0.09284766908852593),
 (143, 0.06868028197434452),
 (144, 0.05407380704358751),
 (145, 0.022680460581325723),
 (146, 0.017099639201419235),
 (147, 0.06415002990995841),
 (148, 0.10660035817780521),
 (149, 0.1735852146410985),
 (150, 0.18750000000000003),
 (151, 0.20833333333333331),
 (152, 0.06537204504606134),
 (153, 0.08606629658238703),
 (154, 0.034752402342845795),
 (155, 0.0),
 (156, 0.06565321642986127),
 (157, 0.10910894511799618),
 (158, 0.1543033499620919),
 (159, 0.07106690545187014),
 (160, 0.09558988911273406),
 (161, 0.03553345272593507),
 (162, 0.03726779962499649),
 (163, 0.053376051268362375),
 (164, 0.09128709291752768),
 (165, 0.04914731871829904),
 (166, 0.11973686801784994),
 (167, 0.07106690545187014),
 (168, 0.16012815380508713),
 (169, 0.11904761904761904),
 (170, 0.09157370929912602),
 (171, 0.029934217004462485),
 (172, 0.15294382258037448),
 (173, 0.024845199749997663),
 (174, 0.1126872339638022),
 (175, 0.05143444998736397),
 (176, 0.0314970394174356),
 (177, 0.0),
 (178, 0.025717224993681984),
 (179, 0.07453559924999298),
 (180, 0.023112508176051212),
 (181, 0.023570226039551584),
 (182, 0.10814761408717502),
 (183, 0.07453559924999298),
 (184, 0.1800205749557739),
 (185, 0.0563436169819011),
 (186, 0.0401286176952564),
 (187, 0.14506471329641485),
 (188, 0.022680460581325723),
 (189, 0.08606629658238703),
 (190, 0.08268982305947231),
 (191, 0.05143444998736397),
 (192, 0.0),
 (193, 0.08679260732054925),
 (194, 0.0),
 (195, 0.06537204504606134),
 (196, 0.05892556509887895),
 (197, 0.047619047619047616),
 (198, 0.06189844605901729),
 (199, 0.11556254088025605),
 (200, 0.08084520834544431),
 (201, 0.0),
 (202, 0.03553345272593507),
 (203, 0.09128709291752768),
 (204, 0.026028960314767677),
 (205, 0.08333333333333333),
 (206, 0.0962250448649376),
 (207, 0.08574929257125441),
 (208, 0.17213259316477406),
 (209, 0.03823595564509362),
 (210, 0.053376051268362375),
 (211, 0.027036903521793755),
 (212, 0.07537783614444091),
 (213, 0.06509445549041193),
 (214, 0.029462782549439476),
 (215, 0.07293249574894728),
 (216, 0.06415002990995841),
 (217, 0.04578685464956301),
 (218, 0.043033148291193514),
 (219, 0.06950480468569159),
 (220, 0.18898223650461357),
 (221, 0.024845199749997663),
 (222, 0.08989331499509895),
 (223, 0.08451542547285165),
 (224, 0.06350006350009524),
 (225, 0.052057920629535355),
 (226, 0.030949223029508643),
 (227, 0.09622504486493762),
 (228, 0.1270821419438372),
 (229, 0.07698003589195009),
 (230, 0.08268982305947231),
 (231, 0.0),
 (232, 0.1217161238900369),
 (233, 0.10910894511799618),
 (234, 0.06868028197434452),
 (235, 0.05892556509887895),
 (236, 0.09622504486493762),
 (237, 0.07273929674533079),
 (238, 0.11867816581938531),
 (239, 0.10758287072798378),
 (240, 0.049690399499995326),
 (241, 0.08333333333333333),
 (242, 0.09622504486493762),
 (243, 0.10050378152592121),
 (244, 0.06415002990995841),
 (245, 0.09128709291752768),
 (246, 0.06622661785325219),
 (247, 0.0),
 (248, 0.04714045207910317),
 (249, 0.14547859349066158),
 (250, 0.0),
 (251, 0.046225016352102424),
 (252, 0.022893427324781505),
 (253, 0.06509445549041193),
 (254, 0.08111071056538127),
 (255, 0.0),
 (256, 0.08084520834544431),
 (257, 0.08574929257125441),
 (258, 0.023338001400466827),
 (259, 0.06537204504606134),
 (260, 0.2434322477800738),
 (261, 0.025717224993681984),
 (262, 0.07142857142857142),
 (263, 0.10425720702853739),
 (264, 0.0),
 (265, 0.029934217004462485),
 (266, 0.1111111111111111),
 (267, 0.07453559924999298),
 (268, 0.027777777777777776),
 (269, 0.03268602252303067),
 (270, 0.10286889997472794),
 (271, 0.08006407690254357),
 (272, 0.030949223029508643),
 (273, 0.023809523809523808),
 (274, 0.07909649964604158),
 (275, 0.12830005981991682),
 (276, 0.06804138174397717),
 (277, 0.06565321642986127),
 (278, 0.12858612496840993),
 (279, 0.1270821419438372),
 (280, 0.0),
 (281, 0.07372097807744857),
 (282, 0.06085806194501845),
 (283, 0.0),
 (284, 0.019920476822239894),
 (285, 0.022893427324781505),
 (286, 0.022473328748774737),
 (287, 0.027777777777777776),
 (288, 0.0),
 (289, 0.050251890762960605),
 (290, 0.06804138174397717),
 (291, 0.05270462766947299),
 (292, 0.10206207261596575),
 (293, 0.032075014954979206),
 (294, 0.12379689211803457),
 (295, 0.1126872339638022),
 (296, 0.0401286176952564),
 (297, 0.048112522432468816),
 (298, 0.0),
 (299, 0.041666666666666664),
 (300, 0.18220272220337375),
 (301, 0.1805787796286538),
 (302, 0.05802588531856595),
 (303, 0.029934217004462485),
 (304, 0.07147416898918632),
 (305, 0.19205531989934396),
 (306, 0.09284766908852593),
 (307, 0.10482848367219183),
 (308, 0.06950480468569159),
 (309, 0.06537204504606134),
 (310, 0.03533326266687867),
 (311, 0.15811388300841894),
 (312, 0.1126872339638022),
 (313, 0.07856742013183862),
 (314, 0.0),
 (315, 0.0944911182523068),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.07453559924999298),
 (320, 0.03333333333333333),
 (321, 0.0),
 (322, 0.2253744679276044),
 (323, 0.03268602252303067),
 (324, 0.026352313834736494),
 (325, 0.10910894511799618),
 (326, 0.05892556509887895),
 (327, 0.029462782549439476),
 (328, 0.0),
 (329, 0.08574929257125441),
 (330, 0.1126872339638022),
 (331, 0.050251890762960605),
 (332, 0.14506471329641488),
 (333, 0.030949223029508643),
 (334, 0.10959932487023819),
 (335, 0.05555555555555555),
 (336, 0.07647191129018724),
 (337, 0.024056261216234408),
 (338, 0.0),
 (339, 0.05892556509887895),
 (340, 0.05143444998736397),
 (341, 0.0629940788348712),
 (342, 0.13471506281091267),
 (343, 0.022680460581325723),
 (344, 0.03268602252303067),
 (345, 0.023570226039551584),
 (346, 0.0),
 (347, 0.0),
 (348, 0.06666666666666667),
 (349, 0.1),
 (350, 0.05479966243511909),
 (351, 0.0),
 (352, 0.029934217004462485),
 (353, 0.024845199749997663),
 (354, 0.0),
 (355, 0.0401286176952564),
 (356, 0.09284766908852593),
 (357, 0.0),
 (358, 0.06537204504606134),
 (359, 0.03553345272593507),
 (360, 0.0),
 (361, 0.057166195047502935),
 (362, 0.1),
 (363, 0.0890870806374748),
 (364, 0.026028960314767677),
 (365, 0.08219949365267865),
 (366, 0.06085806194501845),
 (367, 0.0),
 (368, 0.13608276348795434),
 (369, 0.14291548761875733),
 (370, 0.05802588531856595),
 (371, 0.10286889997472794),
 (372, 0.05407380704358751),
 (373, 0.18633899812498245),
 (374, 0.0445435403187374),
 (375, 0.043033148291193514),
 (376, 0.048621663832631515),
 (377, 0.0),
 (378, 0.0),
 (379, 0.052999894000318),
 (380, 0.029012942659282975),
 (381, 0.09245003270420485),
 (382, 0.0),
 (383, 0.05143444998736397),
 (384, 0.03333333333333333),
 (385, 0.0),
 (386, 0.023112508176051212),
 (387, 0.027399831217559546),
 (388, 0.0),
 (389, 0.10425720702853739),
 (390, 0.028583097523751468),
 (391, 0.06108472217815261),
 (392, 0.03268602252303067),
 (393, 0.0),
 (394, 0.026688025634181187),
 (395, 0.05802588531856595),
 (396, 0.023809523809523808),
 (397, 0.057166195047502935),
 (398, 0.0),
 (399, 0.026352313834736494),
 (400, 0.10425720702853739),
 (401, 0.032075014954979206),
 (402, 0.06085806194501845),
 (403, 0.10942202738310211),
 (404, 0.06666666666666667),
 (405, 0.029934217004462485),
 (406, 0.021884405476620423),
 (407, 0.022075539284417398),
 (408, 0.036369648372665396),
 (409, 0.0),
 (410, 0.10050378152592121),
 (411, 0.0563436169819011),
 (412, 0.10286889997472794),
 (413, 0.1388888888888889),
 (414, 0.03268602252303067),
 (415, 0.07066652533375734),
 (416, 0.0563436169819011),
 (417, 0.03333333333333333),
 (418, 0.03928371006591931),
 (419, 0.07715167498104596),
 (420, 0.12858612496840993),
 (421, 0.0),
 (422, 0.14907119849998596),
 (423, 0.052057920629535355),
 (424, 0.041344911529736156),
 (425, 0.07142857142857142),
 (426, 0.06154574548966636),
 (427, 0.029462782549439476),
 (428, 0.05976143046671968),
 (429, 0.0),
 (430, 0.05143444998736397),
 (431, 0.026028960314767677),
 (432, 0.1256297269074015),
 (433, 0.03553345272593507),
 (434, 0.0),
 (435, 0.04042260417272216),
 (436, 0.0),
 (437, 0.029462782549439476),
 (438, 0.029462782549439476),
 (439, 0.032075014954979206),
 (440, 0.029012942659282975),
 (441, 0.0314970394174356),
 (442, 0.04914731871829904),
 (443, 0.05892556509887895),
 (444, 0.0),
 (445, 0.029462782549439476),
 (446, 0.026352313834736494),
 (447, 0.024310831916315757),
 (448, 0.026028960314767677),
 (449, 0.05986843400892497),
 (450, 0.026352313834736494),
 (451, 0.026688025634181187),
 (452, 0.0314970394174356),
 (453, 0.027036903521793755),
 (454, 0.1256297269074015),
 (455, 0.025125945381480302),
 (456, 0.07071067811865475),
 (457, 0.08703882797784893),
 (458, 0.048112522432468816),
 (459, 0.036369648372665396),
 (460, 0.029012942659282975),
 (461, 0.18633899812498245),
 (462, 0.0),
 (463, 0.034752402342845795),
 (464, 0.0),
 (465, 0.0),
 (466, 0.2132007163556104),
 (467, 0.09157370929912602),
 (468, 0.030949223029508643),
 (469, 0.07001400420140048),
 (470, 0.049690399499995326),
 (471, 0.08333333333333333),
 (472, 0.08574929257125441),
 (473, 0.10286889997472794),
 (474, 0.0),
 (475, 0.06868028197434452),
 (476, 0.10910894511799618),
 (477, 0.0),
 (478, 0.03901371573204352),
 (479, 0.09496714704969829),
 (480, 0.05270462766947299),
 (481, 0.0),
 (482, 0.0314970394174356),
 (483, 0.13608276348795434),
 (484, 0.03726779962499649),
 (485, 0.05555555555555555),
 (486, 0.058520573598065284),
 (487, 0.15294382258037448),
 (488, 0.07500586006173493),
 (489, 0.0),
 (490, 0.14907119849998596),
 (491, 0.08753762190648169),
 (492, 0.06085806194501845),
 (493, 0.019641855032959656),
 (494, 0.0),
 (495, 0.22360679774997894),
 (496, 0.0),
 (497, 0.0),
 (498, 0.06950480468569159),
 (499, 0.0),
 (500, 0.02817180849095055),
 (501, 0.0890870806374748),
 (502, 0.15249857033260467),
 (503, 0.08333333333333333),
 (504, 0.0),
 (505, 0.14547859349066158),
 (506, 0.03823595564509362),
 (507, 0.2518277005725965),
 (508, 0.1160517706371319),
 (509, 0.026028960314767677),
 (510, 0.10814761408717502),
 (511, 0.1),
 (512, 0.0629940788348712),
 (513, 0.1126872339638022),
 (514, 0.05802588531856595),
 (515, 0.027399831217559546),
 (516, 0.026352313834736494),
 (517, 0.0),
 (518, 0.05479966243511909),
 (519, 0.0),
 (520, 0.0),
 (521, 0.029934217004462485),
 (522, 0.0),
 (523, 0.05270462766947299),
 (524, 0.0),
 (525, 0.025416428388767443),
 (526, 0.0),
 (527, 0.0),
 (528, 0.024310831916315757),
 (529, 0.12858612496840993),
 (530, 0.10425720702853739),
 (531, 0.048621663832631515),
 (532, 0.022893427324781505),
 (533, 0.06950480468569159),
 (534, 0.09245003270420485),
 (535, 0.1111111111111111),
 (536, 0.07808688094430304),
 (537, 0.07106690545187014),
 (538, 0.0),
 (539, 0.26940795304016235),
 (540, 0.0563436169819011),
 (541, 0.09072184232530289),
 (542, 0.03955938860646177),
 (543, 0.07905694150420949),
 (544, 0.06085806194501845),
 (545, 0.029934217004462485),
 (546, 0.06804138174397717),
 (547, 0.08703882797784893),
 (548, 0.0),
 (549, 0.1270821419438372),
 (550, 0.02817180849095055),
 (551, 0.0445435403187374),
 (552, 0.0),
 (553, 0.034020690871988585),
 (554, 0.0),
 (555, 0.04926646390821465),
 (556, 0.030429030972509225),
 (557, 0.14506471329641488),
 (558, 0.0),
 (559, 0.03268602252303067),
 (560, 0.045360921162651446),
 (561, 0.03726779962499649),
 (562, 0.0),
 (563, 0.027399831217559546),
 (564, 0.10206207261596575),
 (565, 0.046676002800933654),
 (566, 0.024845199749997663),
 (567, 0.030949223029508643),
 (568, 0.1496710850223124),
 (569, 0.023809523809523808),
 (570, 0.07856742013183862),
 (571, 0.021884405476620423),
 (572, 0.08606629658238703),
 (573, 0.0222717701593687),
 (574, 0.024845199749997663),
 (575, 0.05892556509887895),
 (576, 0.029012942659282975),
 (577, 0.15214515486254612),
 (578, 0.047619047619047616),
 (579, 0.1259881576697424),
 (580, 0.025717224993681984),
 (581, 0.17376201171422898),
 (582, 0.24056261216234406),
 (583, 0.052057920629535355),
 (584, 0.050251890762960605),
 (585, 0.0),
 (586, 0.047619047619047616),
 (587, 0.10286889997472794),
 (588, 0.029934217004462485),
 (589, 0.08399210511316159),
 (590, 0.036369648372665396),
 (591, 0.07808688094430304),
 (592, 0.025717224993681984),
 (593, 0.0),
 (594, 0.05555555555555555),
 (595, 0.13344012817090595),
 (596, 0.09622504486493763),
 (597, 0.05892556509887895),
 (598, 0.04042260417272216),
 (599, 0.03367175148507369),
 (600, 0.07372097807744857),
 (601, 0.036588086663230115),
 (602, 0.045360921162651446),
 (603, 0.0563436169819011),
 (604, 0.06950480468569159),
 (605, 0.0),
 (606, 0.0),
 (607, 0.06509445549041193),
 (608, 0.0),
 (609, 0.048112522432468816),
 (610, 0.059339082909692656),
 (611, 0.02457365935914952),
 (612, 0.07001400420140048),
 (613, 0.04042260417272216),
 (614, 0.06085806194501845),
 (615, 0.034752402342845795),
 (616, 0.0),
 (617, 0.05555555555555555),
 (618, 0.10050378152592121),
 (619, 0.0),
 (620, 0.0),
 (621, 0.07273929674533079),
 (622, 0.0222717701593687),
 (623, 0.0),
 (624, 0.11785113019775793),
 (625, 0.034020690871988585),
 (626, 0.08451542547285165),
 (627, 0.12126781251816647),
 (628, 0.0),
 (629, 0.04914731871829904),
 (630, 0.025416428388767443),
 (631, 0.026688025634181187),
 (632, 0.08333333333333333),
 (633, 0.023570226039551584),
 (634, 0.08838834764831843),
 (635, 0.07624928516630233),
 (636, 0.028583097523751468),
 (637, 0.05407380704358751),
 (638, 0.03553345272593507),
 (639, 0.0),
 (640, 0.05270462766947299),
 (641, 0.0),
 (642, 0.0),
 (643, 0.1111111111111111),
 (644, 0.05802588531856595),
 (645, 0.048112522432468816),
 (646, 0.0563436169819011),
 (647, 0.052057920629535355),
 (648, 0.03333333333333333),
 (649, 0.0),
 (650, 0.0),
 (651, 0.0),
 (652, 0.019641855032959656),
 (653, 0.1336306209562122),
 (654, 0.08989331499509895),
 (655, 0.025416428388767443),
 (656, 0.0),
 (657, 0.037037037037037035),
 (658, 0.053376051268362375),
 (659, 0.027399831217559546),
 (660, 0.10910894511799618),
 (661, 0.17071583991052797),
 (662, 0.0),
 (663, 0.0),
 (664, 0.06537204504606134),
 (665, 0.07537783614444091),
 (666, 0.05270462766947299),
 (667, 0.0),
 (668, 0.07106690545187014),
 (669, 0.03823595564509362),
 (670, 0.01756820922315766),
 (671, 0.05407380704358751),
 (672, 0.0563436169819011),
 (673, 0.022893427324781505),
 (674, 0.07537783614444091),
 (675, 0.052057920629535355),
 (676, 0.034752402342845795),
 (677, 0.027399831217559546),
 (678, 0.06415002990995841),
 (679, 0.0),
 (680, 0.08333333333333333),
 (681, 0.03726779962499649),
 (682, 0.024310831916315757),
 (683, 0.05143444998736397),
 (684, 0.0),
 (685, 0.03823595564509362),
 (686, 0.0),
 (687, 0.1178511301977579),
 (688, 0.050832856777534886),
 (689, 0.0),
 (690, 0.027777777777777776),
 (691, 0.09805806756909201),
 (692, 0.12028130608117205),
 (693, 0.0),
 (694, 0.022680460581325723),
 (695, 0.07106690545187014),
 (696, 0.0),
 (697, 0.0),
 (698, 0.023570226039551584),
 (699, 0.0),
 (700, 0.032075014954979206),
 (701, 0.06415002990995841),
 (702, 0.02457365935914952),
 (703, 0.020833333333333332),
 (704, 0.07453559924999299),
 (705, 0.025717224993681984),
 (706, 0.026352313834736494),
 (707, 0.0),
 (708, 0.025125945381480302),
 (709, 0.0),
 (710, 0.045360921162651446),
 (711, 0.06950480468569159),
 (712, 0.0),
 (713, 0.028583097523751468),
 (714, 0.0),
 (715, 0.10660035817780521),
 (716, 0.036369648372665396),
 (717, 0.0),
 (718, 0.046225016352102424),
 (719, 0.0),
 (720, 0.02817180849095055),
 (721, 0.034020690871988585),
 (722, 0.0),
 (723, 0.026688025634181187),
 (724, 0.026028960314767677),
 (725, 0.0),
 (726, 0.0),
 (727, 0.03615507630310936),
 (728, 0.07537783614444091),
 (729, 0.0),
 (730, 0.01642215463607155),
 (731, 0.05555555555555555),
 (732, 0.07905694150420949),
 (733, 0.045360921162651446),
 (734, 0.050832856777534886),
 (735, 0.049690399499995326),
 (736, 0.03268602252303067),
 (737, 0.08219949365267865),
 (738, 0.0),
 (739, 0.041666666666666664),
 (740, 0.10675210253672475),
 (741, 0.05986843400892497),
 (742, 0.034752402342845795),
 (743, 0.026352313834736494),
 (744, 0.06950480468569159),
 (745, 0.0629940788348712),
 (746, 0.08703882797784893),
 (747, 0.023570226039551584),
 (748, 0.03928371006591931),
 (749, 0.0),
 (750, 0.052057920629535355),
 (751, 0.04042260417272216),
 (752, 0.07537783614444091),

In [280]:
new[new['title'] == 'The Lego Movie'].index[0]

744

In [300]:
def recommend(movie):
    movie_index = new[new['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key = lambda x: x[1])[1:6]
    
    for i in movies_list:
        print(new.iloc[i[0]].title)

In [302]:
recommend('Gandhi')

Gandhi, My Father
The Wind That Shakes the Barley
A Passage to India
Guiana 1838
Ramanujan

In [276]:
import pickle

In [264]:
pickle.dump(new,open('movie_list.pkl','wb'))

In [268]:
new['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [260]:
pickle.dump(new.to_dict(),open('movie_dict.pkl','wb'))

In [304]:
pickle.dump (similarity,open('similarity.pkl','wb'))